parameters:
# Здесь могут быть параметры бандла
  flexycms.uploads_path: '/public/uploads/embedded'

services:

  # Конфигурация для всех сервисов  этого файла по умолчанию
  _defaults:
    autowire: true
    autoconfigure: true

  # Регистрируем контроллеры бандла, сервисы и репозитории как DI-сервисы
  flexycms\FlexyFilemanagerBundle\Service\FileManagerService:
    arguments:
      $uploadPath: '%uploads_path%'

  flexycms\FlexyFilemanagerBundle\Service\ImageManagerService:
    arguments:
      $uploadPath: '%uploads_path%'

  flexycms\FlexyFilemanagerBundle\Controller\FilemanagerController: ~
